---
volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  acme:

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      # Nginx was complaining about this in the logs.
      - TRUST_DOWNSTREAM_PROXY=false
    volumes:
      # Make these available for acme-companion
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      # Don't love having the docker socket mounted into a public container.
      # It _is_ possible to run this as nginx + docker-gen.
      # TODO: look into doing this once this POC is done.
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=${DEFAULT_LETSENCRYPT_EMAIL}
    volumes_from:
      - nginx-proxy
    volumes:
      - nginx-certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
