---
volumes:
  nextcloud-data:
  nextcloud-db:

services:
  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    ports:
      - ${NEXTCLOUD_PORT}:80
    # This is needed for nginx-proxy
    expose:
      - ${NEXTCLOUD_PORT}
    volumes:
      - nextcloud-data:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=nextcloud-db
      # This is needed for nginx-proxy
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      # Prevent this from being accessed from the public internet
      - NETWORK_ACCESS=internal
    env_file:
      - nextcloud.env
    depends_on:
      - nextcloud-db
    restart: unless-stopped

  nextcloud-db:
    image: mariadb:10.6
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      # Prevent this from being accessed from the public internet
      - NETWORK_ACCESS=internal
    env_file:
      - nextcloud.env
    restart: unless-stopped

  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
