---
volumes:
  nextcloud-data:
  nextcloud-db:

services:
  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    ports:
      - ${NEXTCLOUD_PORT}:80
#    # This is needed for nginx-proxy
#    expose:
#      - ${NEXTCLOUD_PORT}
    volumes:
      - nextcloud-data:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=nextcloud-db
#      # nginx-proxy
#      - VIRTUAL_HOST=${NEXTCLOUD_HOST}
#      - VIRTUAL_PORT=${NEXTCLOUD_PORT}
#      # acme-companion
#      - LETSENCRYPT_HOST=${NEXTCLOUD_HOST}
#      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      - nextcloud-db
#      - nginx-proxy
    restart: unless-stopped

  nextcloud-db:
    image: mariadb:10.6
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    restart: unless-stopped
