---
volumes:
  nextcloud-data:
  nextcloud-db:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  acme-script:

services:
  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    ports:
      - ${NEXTCLOUD_PORT}:80
    # This is needed for nginx-proxy
    expose:
      - ${NEXTCLOUD_PORT}
    volumes:
      - nextcloud-data:/var/www/html
    env_file:
      - nextcloud.env
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=nextcloud-db
      # nginx-proxy
      - VIRTUAL_HOST=${NEXTCLOUD_HOST}
      - VIRTUAL_PORT=${NEXTCLOUD_PORT}
      # acme-companion
      - LETSENCRYPT_HOST=${NEXTCLOUD_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      # Prevent external connections to container.
      - NETWORK_ACCESS=internal
    depends_on:
      - nextcloud-db
      - nginx-proxy
    restart: unless-stopped

  nextcloud-db:
    image: mariadb:10.6
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    env_file:
      - nextcloud.env
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      # Prevent external connections to container.
      - NETWORK_ACCESS=internal
    restart: unless-stopped

  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Make these available for acme-companion
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      # Don't love having the docker socket mounted into a public container.
      # It _is_ possible to run this as nginx + docker-gen.
      # TODO: look into doing this once this POC is done.
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    env_file:
      nginx-proxy.env
    environment:
      - DEFAULT_EMAIL=${DEFAULT_LETSENCRYPT_EMAIL}
    volumes_from:
      - nginx-proxy
    volumes:
      - nginx-certs:/etc/nginx/certs:rw
      - acme-script:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
