---
volumes:
  data:
  db:

services:
  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    # This is needed for nginx-proxy
    expose:
      - 80
    volumes:
      - data:/var/www/html
    environment:
      # Admin
      - NEXTCLOUD_ADMIN_USER=${ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      # Database
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=nextcloud-db
      # nginx-proxy
      - VIRTUAL_HOST=${NEXTCLOUD_HOST}
      - VIRTUAL_PORT=80
      # acme-companion
      - LETSENCRYPT_HOST=${NEXTCLOUD_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - nextcloud
      - nginx-proxy
    depends_on:
      - nextcloud-db
    restart: unless-stopped

  nextcloud-db:
    image: mariadb:10.6
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    networks:
      - nextcloud
    restart: unless-stopped

networks:
  nextcloud:
    name: nextcloud
  nginx-proxy:
    name: nginx-proxy
    external: true
